packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  prisma: true
  sharp: true
  '@parcel/watcher': false
  '@scarf/scarf': false
  unrs-resolver: false
  msgpackr-extract: false
