import type { MissionStatus } from '../../generated/prisma/client';

export const MISSION_TRANSITIONS: Readonly<Record<MissionStatus, readonly MissionStatus[]>> = {
  DRAFT: ['ASSIGNED', 'CANCELLED'],
  ASSIGNED: ['WAITING_FOR_VEHICLE', 'CANCELLED'],
  WAITING_FOR_VEHICLE: ['VEHICLE_ARRIVED', 'CANCELLED'],
  VEHICLE_ARRIVED: ['LOADING', 'CANCELLED'],
  LOADING: ['LOADED', 'CANCELLED'],
  LOADED: ['DEPARTED', 'CANCELLED'],
  DEPARTED: ['IN_TRANSIT', 'CANCELLED'],
  IN_TRANSIT: ['AT_STOP', 'CANCELLED'],
  AT_STOP: ['DELIVERING', 'CANCELLED'],
  DELIVERING: ['AT_STOP', 'DELIVERED', 'CANCELLED'],
  DELIVERED: ['OPERATIONALLY_CLOSED'],
  OPERATIONALLY_CLOSED: ['ACCOUNTING_READY'],
  ACCOUNTING_READY: ['CLOSED'],
  CLOSED: [],
  CANCELLED: [],
};
